// The actual exports of this module are generated by the transformer,
// this file only exists so that you can import isA/typeCheckFor functions

throw new Error(
  'It looks like you have forgotten to register the transform for ts-type-checked!\n\nPlease look at the installation guide to see how to do that for your project:\n\nhttps://www.npmjs.com/package/ts-type-checked#installation',
);
